// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeLights.proto

package com.SmartHome.grpc;

public interface APILightsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APILightsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>int32 responseCode = 2;</code>
   */
  int getResponseCode();
}
