// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeLights.proto

package com.SmartHome.grpc;

public interface hallLightsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hallLightsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hallLightsOn = 1;</code>
   */
  String getHallLightsOn();
  /**
   * <code>string hallLightsOn = 1;</code>
   */
  com.google.protobuf.ByteString
      getHallLightsOnBytes();

  /**
   * <code>string hallLightsOff = 2;</code>
   */
  String getHallLightsOff();
  /**
   * <code>string hallLightsOff = 2;</code>
   */
  com.google.protobuf.ByteString
      getHallLightsOffBytes();

  /**
   * <code>int32 numberOfLights = 3;</code>
   */
  int getNumberOfLights();

  /**
   * <code>string status = 4;</code>
   */
  String getStatus();
  /**
   * <code>string status = 4;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
