// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeLights.proto

package com.SmartHome.grpc;

public final class HomeLights {
  private HomeLights() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hallLightsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hallLightsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sittingRoomLightsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sittingRoomLightsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kitchenLightsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kitchenLightsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_timerLightsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_timerLightsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APILightsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APILightsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIResponseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIResponseRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020homeLights.proto\"9\n\022lightStatusRequest" +
      "\022\020\n\010lightsOn\030\001 \001(\t\022\021\n\tlightsOff\030\002 \001(\t\"h\n" +
      "\021hallLightsRequest\022\024\n\014hallLightsOn\030\001 \001(\t" +
      "\022\025\n\rhallLightsOff\030\002 \001(\t\022\026\n\016numberOfLight" +
      "s\030\003 \001(\005\022\016\n\006status\030\004 \001(\t\"}\n\030sittingRoomLi" +
      "ghtsRequest\022\033\n\023sittingRoomLightsOn\030\001 \001(\t" +
      "\022\034\n\024sittingRoomLightsOff\030\002 \001(\t\022\026\n\016number" +
      "OfLights\030\003 \001(\005\022\016\n\006status\030\004 \001(\t\"q\n\024kitche" +
      "nLightsRequest\022\027\n\017KitchenLightsOn\030\001 \001(\t\022" +
      "\030\n\020KitchenLightsOff\030\002 \001(\t\022\026\n\016numberOfLig" +
      "hts\030\003 \001(\005\022\016\n\006status\030\004 \001(\t\"}\n\022timerLights" +
      "Request\022\030\n\020holidaysLightsOn\030\001 \001(\t\022\031\n\021hol" +
      "idaysLightsOff\030\002 \001(\t\022\017\n\007dayTime\030\003 \001(\005\022\021\n" +
      "\tnightTime\030\004 \001(\005\022\016\n\006status\030\005 \001(\t\"B\n\021APIL" +
      "ightsResponse\022\027\n\017responseMessage\030\001 \001(\t\022\024" +
      "\n\014responseCode\030\002 \001(\005\"C\n\022APIResponseReque" +
      "st\022\027\n\017responsemessage\030\001 \001(\t\022\024\n\014responseC" +
      "ode\030\002 \001(\0052\263\002\n\nhomeLights\0227\n\013lightStatus\022" +
      "\023.lightStatusRequest\032\023.APIResponseReques" +
      "t\0224\n\nhallLights\022\022.hallLightsRequest\032\022.AP" +
      "ILightsResponse\022B\n\021sittingRoomLights\022\031.s" +
      "ittingRoomLightsRequest\032\022.APILightsRespo" +
      "nse\022:\n\rkitchenLights\022\025.kitchenLightsRequ" +
      "est\032\022.APILightsResponse\0226\n\013timerLights\022\023" +
      ".timerLightsRequest\032\022.APILightsResponseB" +
      "\026\n\022com.SmartHome.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lightStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lightStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightStatusRequest_descriptor,
        new String[] { "LightsOn", "LightsOff", });
    internal_static_hallLightsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hallLightsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hallLightsRequest_descriptor,
        new String[] { "HallLightsOn", "HallLightsOff", "NumberOfLights", "Status", });
    internal_static_sittingRoomLightsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sittingRoomLightsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sittingRoomLightsRequest_descriptor,
        new String[] { "SittingRoomLightsOn", "SittingRoomLightsOff", "NumberOfLights", "Status", });
    internal_static_kitchenLightsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_kitchenLightsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kitchenLightsRequest_descriptor,
        new String[] { "KitchenLightsOn", "KitchenLightsOff", "NumberOfLights", "Status", });
    internal_static_timerLightsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_timerLightsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_timerLightsRequest_descriptor,
        new String[] { "HolidaysLightsOn", "HolidaysLightsOff", "DayTime", "NightTime", "Status", });
    internal_static_APILightsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_APILightsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APILightsResponse_descriptor,
        new String[] { "ResponseMessage", "ResponseCode", });
    internal_static_APIResponseRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_APIResponseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIResponseRequest_descriptor,
        new String[] { "Responsemessage", "ResponseCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
