// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeLights.proto

package com.SmartHome.grpc;

public interface kitchenLightsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kitchenLightsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string KitchenLightsOn = 1;</code>
   */
  String getKitchenLightsOn();
  /**
   * <code>string KitchenLightsOn = 1;</code>
   */
  com.google.protobuf.ByteString
      getKitchenLightsOnBytes();

  /**
   * <code>string KitchenLightsOff = 2;</code>
   */
  String getKitchenLightsOff();
  /**
   * <code>string KitchenLightsOff = 2;</code>
   */
  com.google.protobuf.ByteString
      getKitchenLightsOffBytes();

  /**
   * <code>int32 numberOfLights = 3;</code>
   */
  int getNumberOfLights();

  /**
   * <code>string status = 4;</code>
   */
  String getStatus();
  /**
   * <code>string status = 4;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
