// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeLights.proto

package com.SmartHome.grpc;

public interface lightStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lightsOn = 1;</code>
   */
  String getLightsOn();
  /**
   * <code>string lightsOn = 1;</code>
   */
  com.google.protobuf.ByteString
      getLightsOnBytes();

  /**
   * <code>string lightsOff = 2;</code>
   */
  String getLightsOff();
  /**
   * <code>string lightsOff = 2;</code>
   */
  com.google.protobuf.ByteString
      getLightsOffBytes();
}
