// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeLights.proto

package com.SmartHome.grpc;

/**
 * Protobuf type {@code sittingRoomLightsRequest}
 */
public  final class sittingRoomLightsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sittingRoomLightsRequest)
    sittingRoomLightsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use sittingRoomLightsRequest.newBuilder() to construct.
  private sittingRoomLightsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private sittingRoomLightsRequest() {
    sittingRoomLightsOn_ = "";
    sittingRoomLightsOff_ = "";
    numberOfLights_ = 0;
    status_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private sittingRoomLightsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            sittingRoomLightsOn_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            sittingRoomLightsOff_ = s;
            break;
          }
          case 24: {

            numberOfLights_ = input.readInt32();
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.SmartHome.grpc.HomeLights.internal_static_sittingRoomLightsRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.SmartHome.grpc.HomeLights.internal_static_sittingRoomLightsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.SmartHome.grpc.sittingRoomLightsRequest.class, com.SmartHome.grpc.sittingRoomLightsRequest.Builder.class);
  }

  public static final int SITTINGROOMLIGHTSON_FIELD_NUMBER = 1;
  private volatile Object sittingRoomLightsOn_;
  /**
   * <code>string sittingRoomLightsOn = 1;</code>
   */
  public String getSittingRoomLightsOn() {
    Object ref = sittingRoomLightsOn_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      sittingRoomLightsOn_ = s;
      return s;
    }
  }
  /**
   * <code>string sittingRoomLightsOn = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSittingRoomLightsOnBytes() {
    Object ref = sittingRoomLightsOn_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sittingRoomLightsOn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SITTINGROOMLIGHTSOFF_FIELD_NUMBER = 2;
  private volatile Object sittingRoomLightsOff_;
  /**
   * <code>string sittingRoomLightsOff = 2;</code>
   */
  public String getSittingRoomLightsOff() {
    Object ref = sittingRoomLightsOff_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      sittingRoomLightsOff_ = s;
      return s;
    }
  }
  /**
   * <code>string sittingRoomLightsOff = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSittingRoomLightsOffBytes() {
    Object ref = sittingRoomLightsOff_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sittingRoomLightsOff_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUMBEROFLIGHTS_FIELD_NUMBER = 3;
  private int numberOfLights_;
  /**
   * <code>int32 numberOfLights = 3;</code>
   */
  public int getNumberOfLights() {
    return numberOfLights_;
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private volatile Object status_;
  /**
   * <code>string status = 4;</code>
   */
  public String getStatus() {
    Object ref = status_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 4;</code>
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    Object ref = status_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSittingRoomLightsOnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sittingRoomLightsOn_);
    }
    if (!getSittingRoomLightsOffBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sittingRoomLightsOff_);
    }
    if (numberOfLights_ != 0) {
      output.writeInt32(3, numberOfLights_);
    }
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, status_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSittingRoomLightsOnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sittingRoomLightsOn_);
    }
    if (!getSittingRoomLightsOffBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sittingRoomLightsOff_);
    }
    if (numberOfLights_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, numberOfLights_);
    }
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.SmartHome.grpc.sittingRoomLightsRequest)) {
      return super.equals(obj);
    }
    com.SmartHome.grpc.sittingRoomLightsRequest other = (com.SmartHome.grpc.sittingRoomLightsRequest) obj;

    boolean result = true;
    result = result && getSittingRoomLightsOn()
        .equals(other.getSittingRoomLightsOn());
    result = result && getSittingRoomLightsOff()
        .equals(other.getSittingRoomLightsOff());
    result = result && (getNumberOfLights()
        == other.getNumberOfLights());
    result = result && getStatus()
        .equals(other.getStatus());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SITTINGROOMLIGHTSON_FIELD_NUMBER;
    hash = (53 * hash) + getSittingRoomLightsOn().hashCode();
    hash = (37 * hash) + SITTINGROOMLIGHTSOFF_FIELD_NUMBER;
    hash = (53 * hash) + getSittingRoomLightsOff().hashCode();
    hash = (37 * hash) + NUMBEROFLIGHTS_FIELD_NUMBER;
    hash = (53 * hash) + getNumberOfLights();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.SmartHome.grpc.sittingRoomLightsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.SmartHome.grpc.sittingRoomLightsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.SmartHome.grpc.sittingRoomLightsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.SmartHome.grpc.sittingRoomLightsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.SmartHome.grpc.sittingRoomLightsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.SmartHome.grpc.sittingRoomLightsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.SmartHome.grpc.sittingRoomLightsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.SmartHome.grpc.sittingRoomLightsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.SmartHome.grpc.sittingRoomLightsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.SmartHome.grpc.sittingRoomLightsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.SmartHome.grpc.sittingRoomLightsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.SmartHome.grpc.sittingRoomLightsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.SmartHome.grpc.sittingRoomLightsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sittingRoomLightsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sittingRoomLightsRequest)
      com.SmartHome.grpc.sittingRoomLightsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.SmartHome.grpc.HomeLights.internal_static_sittingRoomLightsRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.SmartHome.grpc.HomeLights.internal_static_sittingRoomLightsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.SmartHome.grpc.sittingRoomLightsRequest.class, com.SmartHome.grpc.sittingRoomLightsRequest.Builder.class);
    }

    // Construct using com.SmartHome.grpc.sittingRoomLightsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      sittingRoomLightsOn_ = "";

      sittingRoomLightsOff_ = "";

      numberOfLights_ = 0;

      status_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.SmartHome.grpc.HomeLights.internal_static_sittingRoomLightsRequest_descriptor;
    }

    @Override
    public com.SmartHome.grpc.sittingRoomLightsRequest getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public com.SmartHome.grpc.sittingRoomLightsRequest build() {
      com.SmartHome.grpc.sittingRoomLightsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.SmartHome.grpc.sittingRoomLightsRequest buildPartial() {
      com.SmartHome.grpc.sittingRoomLightsRequest result = new com.SmartHome.grpc.sittingRoomLightsRequest(this);
      result.sittingRoomLightsOn_ = sittingRoomLightsOn_;
      result.sittingRoomLightsOff_ = sittingRoomLightsOff_;
      result.numberOfLights_ = numberOfLights_;
      result.status_ = status_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.SmartHome.grpc.sittingRoomLightsRequest) {
        return mergeFrom((com.SmartHome.grpc.sittingRoomLightsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.SmartHome.grpc.sittingRoomLightsRequest other) {
      if (other == getDefaultInstance()) return this;
      if (!other.getSittingRoomLightsOn().isEmpty()) {
        sittingRoomLightsOn_ = other.sittingRoomLightsOn_;
        onChanged();
      }
      if (!other.getSittingRoomLightsOff().isEmpty()) {
        sittingRoomLightsOff_ = other.sittingRoomLightsOff_;
        onChanged();
      }
      if (other.getNumberOfLights() != 0) {
        setNumberOfLights(other.getNumberOfLights());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.SmartHome.grpc.sittingRoomLightsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.SmartHome.grpc.sittingRoomLightsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object sittingRoomLightsOn_ = "";
    /**
     * <code>string sittingRoomLightsOn = 1;</code>
     */
    public String getSittingRoomLightsOn() {
      Object ref = sittingRoomLightsOn_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sittingRoomLightsOn_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string sittingRoomLightsOn = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSittingRoomLightsOnBytes() {
      Object ref = sittingRoomLightsOn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sittingRoomLightsOn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sittingRoomLightsOn = 1;</code>
     */
    public Builder setSittingRoomLightsOn(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      sittingRoomLightsOn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sittingRoomLightsOn = 1;</code>
     */
    public Builder clearSittingRoomLightsOn() {

      sittingRoomLightsOn_ = getDefaultInstance().getSittingRoomLightsOn();
      onChanged();
      return this;
    }
    /**
     * <code>string sittingRoomLightsOn = 1;</code>
     */
    public Builder setSittingRoomLightsOnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      sittingRoomLightsOn_ = value;
      onChanged();
      return this;
    }

    private Object sittingRoomLightsOff_ = "";
    /**
     * <code>string sittingRoomLightsOff = 2;</code>
     */
    public String getSittingRoomLightsOff() {
      Object ref = sittingRoomLightsOff_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sittingRoomLightsOff_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string sittingRoomLightsOff = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSittingRoomLightsOffBytes() {
      Object ref = sittingRoomLightsOff_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sittingRoomLightsOff_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sittingRoomLightsOff = 2;</code>
     */
    public Builder setSittingRoomLightsOff(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      sittingRoomLightsOff_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sittingRoomLightsOff = 2;</code>
     */
    public Builder clearSittingRoomLightsOff() {

      sittingRoomLightsOff_ = getDefaultInstance().getSittingRoomLightsOff();
      onChanged();
      return this;
    }
    /**
     * <code>string sittingRoomLightsOff = 2;</code>
     */
    public Builder setSittingRoomLightsOffBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      sittingRoomLightsOff_ = value;
      onChanged();
      return this;
    }

    private int numberOfLights_ ;
    /**
     * <code>int32 numberOfLights = 3;</code>
     */
    public int getNumberOfLights() {
      return numberOfLights_;
    }
    /**
     * <code>int32 numberOfLights = 3;</code>
     */
    public Builder setNumberOfLights(int value) {

      numberOfLights_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numberOfLights = 3;</code>
     */
    public Builder clearNumberOfLights() {

      numberOfLights_ = 0;
      onChanged();
      return this;
    }

    private Object status_ = "";
    /**
     * <code>string status = 4;</code>
     */
    public String getStatus() {
      Object ref = status_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string status = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 4;</code>
     */
    public Builder setStatus(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 4;</code>
     */
    public Builder clearStatus() {

      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string status = 4;</code>
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      status_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sittingRoomLightsRequest)
  }

  // @@protoc_insertion_point(class_scope:sittingRoomLightsRequest)
  private static final com.SmartHome.grpc.sittingRoomLightsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.SmartHome.grpc.sittingRoomLightsRequest();
  }

  public static com.SmartHome.grpc.sittingRoomLightsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<sittingRoomLightsRequest>
      PARSER = new com.google.protobuf.AbstractParser<sittingRoomLightsRequest>() {
    @Override
    public sittingRoomLightsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new sittingRoomLightsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<sittingRoomLightsRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<sittingRoomLightsRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public com.SmartHome.grpc.sittingRoomLightsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

