// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeLights.proto

package com.SmartHome.grpc;

public interface sittingRoomLightsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sittingRoomLightsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sittingRoomLightsOn = 1;</code>
   */
  String getSittingRoomLightsOn();
  /**
   * <code>string sittingRoomLightsOn = 1;</code>
   */
  com.google.protobuf.ByteString
      getSittingRoomLightsOnBytes();

  /**
   * <code>string sittingRoomLightsOff = 2;</code>
   */
  String getSittingRoomLightsOff();
  /**
   * <code>string sittingRoomLightsOff = 2;</code>
   */
  com.google.protobuf.ByteString
      getSittingRoomLightsOffBytes();

  /**
   * <code>int32 numberOfLights = 3;</code>
   */
  int getNumberOfLights();

  /**
   * <code>string status = 4;</code>
   */
  String getStatus();
  /**
   * <code>string status = 4;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
