// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeLights.proto

package com.SmartHome.grpc;

public interface timerLightsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:timerLightsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string holidaysLightsOn = 1;</code>
   */
  String getHolidaysLightsOn();
  /**
   * <code>string holidaysLightsOn = 1;</code>
   */
  com.google.protobuf.ByteString
      getHolidaysLightsOnBytes();

  /**
   * <code>string holidaysLightsOff = 2;</code>
   */
  String getHolidaysLightsOff();
  /**
   * <code>string holidaysLightsOff = 2;</code>
   */
  com.google.protobuf.ByteString
      getHolidaysLightsOffBytes();

  /**
   * <code>int32 dayTime = 3;</code>
   */
  int getDayTime();

  /**
   * <code>int32 nightTime = 4;</code>
   */
  int getNightTime();

  /**
   * <code>string status = 5;</code>
   */
  String getStatus();
  /**
   * <code>string status = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
