// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeLights.proto

package com.SmartHome.grpc;

/**
 * Protobuf type {@code timerLightsRequest}
 */
public  final class timerLightsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:timerLightsRequest)
    timerLightsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use timerLightsRequest.newBuilder() to construct.
  private timerLightsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private timerLightsRequest() {
    holidaysLightsOn_ = "";
    holidaysLightsOff_ = "";
    dayTime_ = 0;
    nightTime_ = 0;
    status_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private timerLightsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            holidaysLightsOn_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            holidaysLightsOff_ = s;
            break;
          }
          case 24: {

            dayTime_ = input.readInt32();
            break;
          }
          case 32: {

            nightTime_ = input.readInt32();
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.SmartHome.grpc.HomeLights.internal_static_timerLightsRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.SmartHome.grpc.HomeLights.internal_static_timerLightsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.SmartHome.grpc.timerLightsRequest.class, com.SmartHome.grpc.timerLightsRequest.Builder.class);
  }

  public static final int HOLIDAYSLIGHTSON_FIELD_NUMBER = 1;
  private volatile Object holidaysLightsOn_;
  /**
   * <code>string holidaysLightsOn = 1;</code>
   */
  public String getHolidaysLightsOn() {
    Object ref = holidaysLightsOn_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      holidaysLightsOn_ = s;
      return s;
    }
  }
  /**
   * <code>string holidaysLightsOn = 1;</code>
   */
  public com.google.protobuf.ByteString
      getHolidaysLightsOnBytes() {
    Object ref = holidaysLightsOn_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      holidaysLightsOn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOLIDAYSLIGHTSOFF_FIELD_NUMBER = 2;
  private volatile Object holidaysLightsOff_;
  /**
   * <code>string holidaysLightsOff = 2;</code>
   */
  public String getHolidaysLightsOff() {
    Object ref = holidaysLightsOff_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      holidaysLightsOff_ = s;
      return s;
    }
  }
  /**
   * <code>string holidaysLightsOff = 2;</code>
   */
  public com.google.protobuf.ByteString
      getHolidaysLightsOffBytes() {
    Object ref = holidaysLightsOff_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      holidaysLightsOff_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DAYTIME_FIELD_NUMBER = 3;
  private int dayTime_;
  /**
   * <code>int32 dayTime = 3;</code>
   */
  public int getDayTime() {
    return dayTime_;
  }

  public static final int NIGHTTIME_FIELD_NUMBER = 4;
  private int nightTime_;
  /**
   * <code>int32 nightTime = 4;</code>
   */
  public int getNightTime() {
    return nightTime_;
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  private volatile Object status_;
  /**
   * <code>string status = 5;</code>
   */
  public String getStatus() {
    Object ref = status_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 5;</code>
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    Object ref = status_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHolidaysLightsOnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, holidaysLightsOn_);
    }
    if (!getHolidaysLightsOffBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, holidaysLightsOff_);
    }
    if (dayTime_ != 0) {
      output.writeInt32(3, dayTime_);
    }
    if (nightTime_ != 0) {
      output.writeInt32(4, nightTime_);
    }
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, status_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHolidaysLightsOnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, holidaysLightsOn_);
    }
    if (!getHolidaysLightsOffBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, holidaysLightsOff_);
    }
    if (dayTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, dayTime_);
    }
    if (nightTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, nightTime_);
    }
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.SmartHome.grpc.timerLightsRequest)) {
      return super.equals(obj);
    }
    com.SmartHome.grpc.timerLightsRequest other = (com.SmartHome.grpc.timerLightsRequest) obj;

    boolean result = true;
    result = result && getHolidaysLightsOn()
        .equals(other.getHolidaysLightsOn());
    result = result && getHolidaysLightsOff()
        .equals(other.getHolidaysLightsOff());
    result = result && (getDayTime()
        == other.getDayTime());
    result = result && (getNightTime()
        == other.getNightTime());
    result = result && getStatus()
        .equals(other.getStatus());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOLIDAYSLIGHTSON_FIELD_NUMBER;
    hash = (53 * hash) + getHolidaysLightsOn().hashCode();
    hash = (37 * hash) + HOLIDAYSLIGHTSOFF_FIELD_NUMBER;
    hash = (53 * hash) + getHolidaysLightsOff().hashCode();
    hash = (37 * hash) + DAYTIME_FIELD_NUMBER;
    hash = (53 * hash) + getDayTime();
    hash = (37 * hash) + NIGHTTIME_FIELD_NUMBER;
    hash = (53 * hash) + getNightTime();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.SmartHome.grpc.timerLightsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.SmartHome.grpc.timerLightsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.SmartHome.grpc.timerLightsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.SmartHome.grpc.timerLightsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.SmartHome.grpc.timerLightsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.SmartHome.grpc.timerLightsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.SmartHome.grpc.timerLightsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.SmartHome.grpc.timerLightsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.SmartHome.grpc.timerLightsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.SmartHome.grpc.timerLightsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.SmartHome.grpc.timerLightsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.SmartHome.grpc.timerLightsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.SmartHome.grpc.timerLightsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code timerLightsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:timerLightsRequest)
      com.SmartHome.grpc.timerLightsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.SmartHome.grpc.HomeLights.internal_static_timerLightsRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.SmartHome.grpc.HomeLights.internal_static_timerLightsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.SmartHome.grpc.timerLightsRequest.class, com.SmartHome.grpc.timerLightsRequest.Builder.class);
    }

    // Construct using com.SmartHome.grpc.timerLightsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      holidaysLightsOn_ = "";

      holidaysLightsOff_ = "";

      dayTime_ = 0;

      nightTime_ = 0;

      status_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.SmartHome.grpc.HomeLights.internal_static_timerLightsRequest_descriptor;
    }

    @Override
    public com.SmartHome.grpc.timerLightsRequest getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public com.SmartHome.grpc.timerLightsRequest build() {
      com.SmartHome.grpc.timerLightsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.SmartHome.grpc.timerLightsRequest buildPartial() {
      com.SmartHome.grpc.timerLightsRequest result = new com.SmartHome.grpc.timerLightsRequest(this);
      result.holidaysLightsOn_ = holidaysLightsOn_;
      result.holidaysLightsOff_ = holidaysLightsOff_;
      result.dayTime_ = dayTime_;
      result.nightTime_ = nightTime_;
      result.status_ = status_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.SmartHome.grpc.timerLightsRequest) {
        return mergeFrom((com.SmartHome.grpc.timerLightsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.SmartHome.grpc.timerLightsRequest other) {
      if (other == getDefaultInstance()) return this;
      if (!other.getHolidaysLightsOn().isEmpty()) {
        holidaysLightsOn_ = other.holidaysLightsOn_;
        onChanged();
      }
      if (!other.getHolidaysLightsOff().isEmpty()) {
        holidaysLightsOff_ = other.holidaysLightsOff_;
        onChanged();
      }
      if (other.getDayTime() != 0) {
        setDayTime(other.getDayTime());
      }
      if (other.getNightTime() != 0) {
        setNightTime(other.getNightTime());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.SmartHome.grpc.timerLightsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.SmartHome.grpc.timerLightsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object holidaysLightsOn_ = "";
    /**
     * <code>string holidaysLightsOn = 1;</code>
     */
    public String getHolidaysLightsOn() {
      Object ref = holidaysLightsOn_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        holidaysLightsOn_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string holidaysLightsOn = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHolidaysLightsOnBytes() {
      Object ref = holidaysLightsOn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        holidaysLightsOn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string holidaysLightsOn = 1;</code>
     */
    public Builder setHolidaysLightsOn(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      holidaysLightsOn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string holidaysLightsOn = 1;</code>
     */
    public Builder clearHolidaysLightsOn() {

      holidaysLightsOn_ = getDefaultInstance().getHolidaysLightsOn();
      onChanged();
      return this;
    }
    /**
     * <code>string holidaysLightsOn = 1;</code>
     */
    public Builder setHolidaysLightsOnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      holidaysLightsOn_ = value;
      onChanged();
      return this;
    }

    private Object holidaysLightsOff_ = "";
    /**
     * <code>string holidaysLightsOff = 2;</code>
     */
    public String getHolidaysLightsOff() {
      Object ref = holidaysLightsOff_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        holidaysLightsOff_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string holidaysLightsOff = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHolidaysLightsOffBytes() {
      Object ref = holidaysLightsOff_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        holidaysLightsOff_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string holidaysLightsOff = 2;</code>
     */
    public Builder setHolidaysLightsOff(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      holidaysLightsOff_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string holidaysLightsOff = 2;</code>
     */
    public Builder clearHolidaysLightsOff() {

      holidaysLightsOff_ = getDefaultInstance().getHolidaysLightsOff();
      onChanged();
      return this;
    }
    /**
     * <code>string holidaysLightsOff = 2;</code>
     */
    public Builder setHolidaysLightsOffBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      holidaysLightsOff_ = value;
      onChanged();
      return this;
    }

    private int dayTime_ ;
    /**
     * <code>int32 dayTime = 3;</code>
     */
    public int getDayTime() {
      return dayTime_;
    }
    /**
     * <code>int32 dayTime = 3;</code>
     */
    public Builder setDayTime(int value) {

      dayTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 dayTime = 3;</code>
     */
    public Builder clearDayTime() {

      dayTime_ = 0;
      onChanged();
      return this;
    }

    private int nightTime_ ;
    /**
     * <code>int32 nightTime = 4;</code>
     */
    public int getNightTime() {
      return nightTime_;
    }
    /**
     * <code>int32 nightTime = 4;</code>
     */
    public Builder setNightTime(int value) {

      nightTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 nightTime = 4;</code>
     */
    public Builder clearNightTime() {

      nightTime_ = 0;
      onChanged();
      return this;
    }

    private Object status_ = "";
    /**
     * <code>string status = 5;</code>
     */
    public String getStatus() {
      Object ref = status_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string status = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 5;</code>
     */
    public Builder setStatus(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 5;</code>
     */
    public Builder clearStatus() {

      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string status = 5;</code>
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      status_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:timerLightsRequest)
  }

  // @@protoc_insertion_point(class_scope:timerLightsRequest)
  private static final com.SmartHome.grpc.timerLightsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.SmartHome.grpc.timerLightsRequest();
  }

  public static com.SmartHome.grpc.timerLightsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<timerLightsRequest>
      PARSER = new com.google.protobuf.AbstractParser<timerLightsRequest>() {
    @Override
    public timerLightsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new timerLightsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<timerLightsRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<timerLightsRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public com.SmartHome.grpc.timerLightsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

