// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeHeating.proto

package com.proto.homeHeating;

public final class HomeHeating {
  private HomeHeating() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_homeHeating_Radiator_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_homeHeating_Radiator_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_homeHeating_radiatorStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_homeHeating_radiatorStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_homeHeating_radiatorToUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_homeHeating_radiatorToUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_homeHeating_radiatorStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_homeHeating_radiatorStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_homeHeating_radiatorDetailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_homeHeating_radiatorDetailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021homeHeating.proto\022\013homeHeating\"\203\001\n\010Rad" +
      "iator\022\022\n\nradiatorId\030\001 \001(\005\022\024\n\014radiatorNam" +
      "e\030\002 \001(\t\022\033\n\023radiatorDescription\030\003 \001(\t\022\030\n\020" +
      "radiatorLocation\030\004 \001(\t\022\026\n\016radiatorStatus" +
      "\030\005 \001(\t\"+\n\025radiatorStatusRequest\022\022\n\nradia" +
      "torId\030\001 \001(\005\"-\n\027radiatorToUpdateRequest\022\022" +
      "\n\nradiatorId\030\001 \001(\005\"A\n\026radiatorStatusResp" +
      "onse\022\'\n\010radiator\030\001 \001(\0132\025.homeHeating.Rad" +
      "iator\"A\n\026radiatorDetailResponse\022\'\n\010radia" +
      "tor\030\001 \001(\0132\025.homeHeating.Radiator2\372\003\n\017rad" +
      "iatorService\022_\n\022showRadiatorStatus\022\".hom" +
      "eHeating.radiatorStatusRequest\032#.homeHea" +
      "ting.radiatorStatusResponse\"\000\022_\n\020setRadi" +
      "atorToLow\022$.homeHeating.radiatorToUpdate" +
      "Request\032#.homeHeating.radiatorDetailResp" +
      "onse\"\000\022b\n\023setRadiatorToMedium\022$.homeHeat" +
      "ing.radiatorToUpdateRequest\032#.homeHeatin" +
      "g.radiatorDetailResponse\"\000\022`\n\021setRadiato" +
      "rToHigh\022$.homeHeating.radiatorToUpdateRe" +
      "quest\032#.homeHeating.radiatorDetailRespon" +
      "se\"\000\022_\n\020setRadiatorToOff\022$.homeHeating.r" +
      "adiatorToUpdateRequest\032#.homeHeating.rad" +
      "iatorDetailResponse\"\000B\031\n\025com.proto.homeH" +
      "eatingP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_homeHeating_Radiator_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_homeHeating_Radiator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_homeHeating_Radiator_descriptor,
        new String[] { "RadiatorId", "RadiatorName", "RadiatorDescription", "RadiatorLocation", "RadiatorStatus", });
    internal_static_homeHeating_radiatorStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_homeHeating_radiatorStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_homeHeating_radiatorStatusRequest_descriptor,
        new String[] { "RadiatorId", });
    internal_static_homeHeating_radiatorToUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_homeHeating_radiatorToUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_homeHeating_radiatorToUpdateRequest_descriptor,
        new String[] { "RadiatorId", });
    internal_static_homeHeating_radiatorStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_homeHeating_radiatorStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_homeHeating_radiatorStatusResponse_descriptor,
        new String[] { "Radiator", });
    internal_static_homeHeating_radiatorDetailResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_homeHeating_radiatorDetailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_homeHeating_radiatorDetailResponse_descriptor,
        new String[] { "Radiator", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
