// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeHeating.proto

package com.proto.homeHeating;

/**
 * Protobuf type {@code homeHeating.radiatorStatusResponse}
 */
public  final class radiatorStatusResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:homeHeating.radiatorStatusResponse)
    radiatorStatusResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use radiatorStatusResponse.newBuilder() to construct.
  private radiatorStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private radiatorStatusResponse() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private radiatorStatusResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.proto.homeHeating.Radiator.Builder subBuilder = null;
            if (radiator_ != null) {
              subBuilder = radiator_.toBuilder();
            }
            radiator_ = input.readMessage(com.proto.homeHeating.Radiator.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(radiator_);
              radiator_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.proto.homeHeating.HomeHeating.internal_static_homeHeating_radiatorStatusResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.proto.homeHeating.HomeHeating.internal_static_homeHeating_radiatorStatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.proto.homeHeating.radiatorStatusResponse.class, com.proto.homeHeating.radiatorStatusResponse.Builder.class);
  }

  public static final int RADIATOR_FIELD_NUMBER = 1;
  private com.proto.homeHeating.Radiator radiator_;
  /**
   * <code>.homeHeating.Radiator radiator = 1;</code>
   */
  public boolean hasRadiator() {
    return radiator_ != null;
  }
  /**
   * <code>.homeHeating.Radiator radiator = 1;</code>
   */
  public com.proto.homeHeating.Radiator getRadiator() {
    return radiator_ == null ? com.proto.homeHeating.Radiator.getDefaultInstance() : radiator_;
  }
  /**
   * <code>.homeHeating.Radiator radiator = 1;</code>
   */
  public com.proto.homeHeating.RadiatorOrBuilder getRadiatorOrBuilder() {
    return getRadiator();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (radiator_ != null) {
      output.writeMessage(1, getRadiator());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (radiator_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRadiator());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.proto.homeHeating.radiatorStatusResponse)) {
      return super.equals(obj);
    }
    com.proto.homeHeating.radiatorStatusResponse other = (com.proto.homeHeating.radiatorStatusResponse) obj;

    boolean result = true;
    result = result && (hasRadiator() == other.hasRadiator());
    if (hasRadiator()) {
      result = result && getRadiator()
          .equals(other.getRadiator());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRadiator()) {
      hash = (37 * hash) + RADIATOR_FIELD_NUMBER;
      hash = (53 * hash) + getRadiator().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.proto.homeHeating.radiatorStatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.homeHeating.radiatorStatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.homeHeating.radiatorStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.homeHeating.radiatorStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.homeHeating.radiatorStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.homeHeating.radiatorStatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.homeHeating.radiatorStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.homeHeating.radiatorStatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.homeHeating.radiatorStatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.proto.homeHeating.radiatorStatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.homeHeating.radiatorStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.homeHeating.radiatorStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.proto.homeHeating.radiatorStatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code homeHeating.radiatorStatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:homeHeating.radiatorStatusResponse)
      com.proto.homeHeating.radiatorStatusResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.homeHeating.HomeHeating.internal_static_homeHeating_radiatorStatusResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.homeHeating.HomeHeating.internal_static_homeHeating_radiatorStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.homeHeating.radiatorStatusResponse.class, com.proto.homeHeating.radiatorStatusResponse.Builder.class);
    }

    // Construct using com.proto.homeHeating.radiatorStatusResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (radiatorBuilder_ == null) {
        radiator_ = null;
      } else {
        radiator_ = null;
        radiatorBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.proto.homeHeating.HomeHeating.internal_static_homeHeating_radiatorStatusResponse_descriptor;
    }

    @Override
    public com.proto.homeHeating.radiatorStatusResponse getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public com.proto.homeHeating.radiatorStatusResponse build() {
      com.proto.homeHeating.radiatorStatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.proto.homeHeating.radiatorStatusResponse buildPartial() {
      com.proto.homeHeating.radiatorStatusResponse result = new com.proto.homeHeating.radiatorStatusResponse(this);
      if (radiatorBuilder_ == null) {
        result.radiator_ = radiator_;
      } else {
        result.radiator_ = radiatorBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.proto.homeHeating.radiatorStatusResponse) {
        return mergeFrom((com.proto.homeHeating.radiatorStatusResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.proto.homeHeating.radiatorStatusResponse other) {
      if (other == getDefaultInstance()) return this;
      if (other.hasRadiator()) {
        mergeRadiator(other.getRadiator());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.proto.homeHeating.radiatorStatusResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.proto.homeHeating.radiatorStatusResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.proto.homeHeating.Radiator radiator_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.proto.homeHeating.Radiator, com.proto.homeHeating.Radiator.Builder, com.proto.homeHeating.RadiatorOrBuilder> radiatorBuilder_;
    /**
     * <code>.homeHeating.Radiator radiator = 1;</code>
     */
    public boolean hasRadiator() {
      return radiatorBuilder_ != null || radiator_ != null;
    }
    /**
     * <code>.homeHeating.Radiator radiator = 1;</code>
     */
    public com.proto.homeHeating.Radiator getRadiator() {
      if (radiatorBuilder_ == null) {
        return radiator_ == null ? com.proto.homeHeating.Radiator.getDefaultInstance() : radiator_;
      } else {
        return radiatorBuilder_.getMessage();
      }
    }
    /**
     * <code>.homeHeating.Radiator radiator = 1;</code>
     */
    public Builder setRadiator(com.proto.homeHeating.Radiator value) {
      if (radiatorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        radiator_ = value;
        onChanged();
      } else {
        radiatorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.homeHeating.Radiator radiator = 1;</code>
     */
    public Builder setRadiator(
        com.proto.homeHeating.Radiator.Builder builderForValue) {
      if (radiatorBuilder_ == null) {
        radiator_ = builderForValue.build();
        onChanged();
      } else {
        radiatorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.homeHeating.Radiator radiator = 1;</code>
     */
    public Builder mergeRadiator(com.proto.homeHeating.Radiator value) {
      if (radiatorBuilder_ == null) {
        if (radiator_ != null) {
          radiator_ =
            com.proto.homeHeating.Radiator.newBuilder(radiator_).mergeFrom(value).buildPartial();
        } else {
          radiator_ = value;
        }
        onChanged();
      } else {
        radiatorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.homeHeating.Radiator radiator = 1;</code>
     */
    public Builder clearRadiator() {
      if (radiatorBuilder_ == null) {
        radiator_ = null;
        onChanged();
      } else {
        radiator_ = null;
        radiatorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.homeHeating.Radiator radiator = 1;</code>
     */
    public com.proto.homeHeating.Radiator.Builder getRadiatorBuilder() {

      onChanged();
      return getRadiatorFieldBuilder().getBuilder();
    }
    /**
     * <code>.homeHeating.Radiator radiator = 1;</code>
     */
    public com.proto.homeHeating.RadiatorOrBuilder getRadiatorOrBuilder() {
      if (radiatorBuilder_ != null) {
        return radiatorBuilder_.getMessageOrBuilder();
      } else {
        return radiator_ == null ?
            com.proto.homeHeating.Radiator.getDefaultInstance() : radiator_;
      }
    }
    /**
     * <code>.homeHeating.Radiator radiator = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.proto.homeHeating.Radiator, com.proto.homeHeating.Radiator.Builder, com.proto.homeHeating.RadiatorOrBuilder>
        getRadiatorFieldBuilder() {
      if (radiatorBuilder_ == null) {
        radiatorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.proto.homeHeating.Radiator, com.proto.homeHeating.Radiator.Builder, com.proto.homeHeating.RadiatorOrBuilder>(
                getRadiator(),
                getParentForChildren(),
                isClean());
        radiator_ = null;
      }
      return radiatorBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:homeHeating.radiatorStatusResponse)
  }

  // @@protoc_insertion_point(class_scope:homeHeating.radiatorStatusResponse)
  private static final com.proto.homeHeating.radiatorStatusResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.proto.homeHeating.radiatorStatusResponse();
  }

  public static com.proto.homeHeating.radiatorStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<radiatorStatusResponse>
      PARSER = new com.google.protobuf.AbstractParser<radiatorStatusResponse>() {
    @Override
    public radiatorStatusResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new radiatorStatusResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<radiatorStatusResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<radiatorStatusResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public com.proto.homeHeating.radiatorStatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

