// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeHeating.proto

package com.proto.homeHeating;

public interface RadiatorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:homeHeating.Radiator)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 radiatorId = 1;</code>
   */
  int getRadiatorId();

  /**
   * <code>string radiatorName = 2;</code>
   */
  String getRadiatorName();
  /**
   * <code>string radiatorName = 2;</code>
   */
  com.google.protobuf.ByteString
      getRadiatorNameBytes();

  /**
   * <code>string radiatorDescription = 3;</code>
   */
  String getRadiatorDescription();
  /**
   * <code>string radiatorDescription = 3;</code>
   */
  com.google.protobuf.ByteString
      getRadiatorDescriptionBytes();

  /**
   * <code>string radiatorLocation = 4;</code>
   */
  String getRadiatorLocation();
  /**
   * <code>string radiatorLocation = 4;</code>
   */
  com.google.protobuf.ByteString
      getRadiatorLocationBytes();

  /**
   * <code>string radiatorStatus = 5;</code>
   */
  String getRadiatorStatus();
  /**
   * <code>string radiatorStatus = 5;</code>
   */
  com.google.protobuf.ByteString
      getRadiatorStatusBytes();
}
