// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeHeating.proto

package com.proto.homeHeating;

public interface radiatorStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:homeHeating.radiatorStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.homeHeating.Radiator radiator = 1;</code>
   */
  boolean hasRadiator();
  /**
   * <code>.homeHeating.Radiator radiator = 1;</code>
   */
  com.proto.homeHeating.Radiator getRadiator();
  /**
   * <code>.homeHeating.Radiator radiator = 1;</code>
   */
  com.proto.homeHeating.RadiatorOrBuilder getRadiatorOrBuilder();
}
