// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeHeating.proto

package com.proto.homeHeating;

public interface radiatorToUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:homeHeating.radiatorToUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 radiatorId = 1;</code>
   */
  int getRadiatorId();
}
