// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeHeating.proto

package com.proto.homeHeating;

/**
 * Protobuf type {@code homeHeating.Radiator}
 */
public  final class Radiator extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:homeHeating.Radiator)
    RadiatorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Radiator.newBuilder() to construct.
  private Radiator(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Radiator() {
    radiatorId_ = 0;
    radiatorName_ = "";
    radiatorDescription_ = "";
    radiatorLocation_ = "";
    radiatorStatus_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Radiator(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            radiatorId_ = input.readInt32();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            radiatorName_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            radiatorDescription_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            radiatorLocation_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            radiatorStatus_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.proto.homeHeating.HomeHeating.internal_static_homeHeating_Radiator_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.proto.homeHeating.HomeHeating.internal_static_homeHeating_Radiator_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.proto.homeHeating.Radiator.class, com.proto.homeHeating.Radiator.Builder.class);
  }

  public static final int RADIATORID_FIELD_NUMBER = 1;
  private int radiatorId_;
  /**
   * <code>int32 radiatorId = 1;</code>
   */
  public int getRadiatorId() {
    return radiatorId_;
  }

  public static final int RADIATORNAME_FIELD_NUMBER = 2;
  private volatile Object radiatorName_;
  /**
   * <code>string radiatorName = 2;</code>
   */
  public String getRadiatorName() {
    Object ref = radiatorName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      radiatorName_ = s;
      return s;
    }
  }
  /**
   * <code>string radiatorName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRadiatorNameBytes() {
    Object ref = radiatorName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      radiatorName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RADIATORDESCRIPTION_FIELD_NUMBER = 3;
  private volatile Object radiatorDescription_;
  /**
   * <code>string radiatorDescription = 3;</code>
   */
  public String getRadiatorDescription() {
    Object ref = radiatorDescription_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      radiatorDescription_ = s;
      return s;
    }
  }
  /**
   * <code>string radiatorDescription = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRadiatorDescriptionBytes() {
    Object ref = radiatorDescription_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      radiatorDescription_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RADIATORLOCATION_FIELD_NUMBER = 4;
  private volatile Object radiatorLocation_;
  /**
   * <code>string radiatorLocation = 4;</code>
   */
  public String getRadiatorLocation() {
    Object ref = radiatorLocation_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      radiatorLocation_ = s;
      return s;
    }
  }
  /**
   * <code>string radiatorLocation = 4;</code>
   */
  public com.google.protobuf.ByteString
      getRadiatorLocationBytes() {
    Object ref = radiatorLocation_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      radiatorLocation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RADIATORSTATUS_FIELD_NUMBER = 5;
  private volatile Object radiatorStatus_;
  /**
   * <code>string radiatorStatus = 5;</code>
   */
  public String getRadiatorStatus() {
    Object ref = radiatorStatus_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      radiatorStatus_ = s;
      return s;
    }
  }
  /**
   * <code>string radiatorStatus = 5;</code>
   */
  public com.google.protobuf.ByteString
      getRadiatorStatusBytes() {
    Object ref = radiatorStatus_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      radiatorStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (radiatorId_ != 0) {
      output.writeInt32(1, radiatorId_);
    }
    if (!getRadiatorNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, radiatorName_);
    }
    if (!getRadiatorDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, radiatorDescription_);
    }
    if (!getRadiatorLocationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, radiatorLocation_);
    }
    if (!getRadiatorStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, radiatorStatus_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (radiatorId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, radiatorId_);
    }
    if (!getRadiatorNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, radiatorName_);
    }
    if (!getRadiatorDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, radiatorDescription_);
    }
    if (!getRadiatorLocationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, radiatorLocation_);
    }
    if (!getRadiatorStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, radiatorStatus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.proto.homeHeating.Radiator)) {
      return super.equals(obj);
    }
    com.proto.homeHeating.Radiator other = (com.proto.homeHeating.Radiator) obj;

    boolean result = true;
    result = result && (getRadiatorId()
        == other.getRadiatorId());
    result = result && getRadiatorName()
        .equals(other.getRadiatorName());
    result = result && getRadiatorDescription()
        .equals(other.getRadiatorDescription());
    result = result && getRadiatorLocation()
        .equals(other.getRadiatorLocation());
    result = result && getRadiatorStatus()
        .equals(other.getRadiatorStatus());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RADIATORID_FIELD_NUMBER;
    hash = (53 * hash) + getRadiatorId();
    hash = (37 * hash) + RADIATORNAME_FIELD_NUMBER;
    hash = (53 * hash) + getRadiatorName().hashCode();
    hash = (37 * hash) + RADIATORDESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getRadiatorDescription().hashCode();
    hash = (37 * hash) + RADIATORLOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getRadiatorLocation().hashCode();
    hash = (37 * hash) + RADIATORSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + getRadiatorStatus().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.proto.homeHeating.Radiator parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.homeHeating.Radiator parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.homeHeating.Radiator parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.homeHeating.Radiator parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.homeHeating.Radiator parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.homeHeating.Radiator parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.homeHeating.Radiator parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.homeHeating.Radiator parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.homeHeating.Radiator parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.proto.homeHeating.Radiator parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.homeHeating.Radiator parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.homeHeating.Radiator parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.proto.homeHeating.Radiator prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code homeHeating.Radiator}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:homeHeating.Radiator)
      com.proto.homeHeating.RadiatorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.homeHeating.HomeHeating.internal_static_homeHeating_Radiator_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.homeHeating.HomeHeating.internal_static_homeHeating_Radiator_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.homeHeating.Radiator.class, com.proto.homeHeating.Radiator.Builder.class);
    }

    // Construct using com.proto.homeHeating.Radiator.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      radiatorId_ = 0;

      radiatorName_ = "";

      radiatorDescription_ = "";

      radiatorLocation_ = "";

      radiatorStatus_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.proto.homeHeating.HomeHeating.internal_static_homeHeating_Radiator_descriptor;
    }

    @Override
    public com.proto.homeHeating.Radiator getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public com.proto.homeHeating.Radiator build() {
      com.proto.homeHeating.Radiator result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.proto.homeHeating.Radiator buildPartial() {
      com.proto.homeHeating.Radiator result = new com.proto.homeHeating.Radiator(this);
      result.radiatorId_ = radiatorId_;
      result.radiatorName_ = radiatorName_;
      result.radiatorDescription_ = radiatorDescription_;
      result.radiatorLocation_ = radiatorLocation_;
      result.radiatorStatus_ = radiatorStatus_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.proto.homeHeating.Radiator) {
        return mergeFrom((com.proto.homeHeating.Radiator)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.proto.homeHeating.Radiator other) {
      if (other == getDefaultInstance()) return this;
      if (other.getRadiatorId() != 0) {
        setRadiatorId(other.getRadiatorId());
      }
      if (!other.getRadiatorName().isEmpty()) {
        radiatorName_ = other.radiatorName_;
        onChanged();
      }
      if (!other.getRadiatorDescription().isEmpty()) {
        radiatorDescription_ = other.radiatorDescription_;
        onChanged();
      }
      if (!other.getRadiatorLocation().isEmpty()) {
        radiatorLocation_ = other.radiatorLocation_;
        onChanged();
      }
      if (!other.getRadiatorStatus().isEmpty()) {
        radiatorStatus_ = other.radiatorStatus_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.proto.homeHeating.Radiator parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.proto.homeHeating.Radiator) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int radiatorId_ ;
    /**
     * <code>int32 radiatorId = 1;</code>
     */
    public int getRadiatorId() {
      return radiatorId_;
    }
    /**
     * <code>int32 radiatorId = 1;</code>
     */
    public Builder setRadiatorId(int value) {

      radiatorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 radiatorId = 1;</code>
     */
    public Builder clearRadiatorId() {

      radiatorId_ = 0;
      onChanged();
      return this;
    }

    private Object radiatorName_ = "";
    /**
     * <code>string radiatorName = 2;</code>
     */
    public String getRadiatorName() {
      Object ref = radiatorName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        radiatorName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string radiatorName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRadiatorNameBytes() {
      Object ref = radiatorName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        radiatorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string radiatorName = 2;</code>
     */
    public Builder setRadiatorName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      radiatorName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string radiatorName = 2;</code>
     */
    public Builder clearRadiatorName() {

      radiatorName_ = getDefaultInstance().getRadiatorName();
      onChanged();
      return this;
    }
    /**
     * <code>string radiatorName = 2;</code>
     */
    public Builder setRadiatorNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      radiatorName_ = value;
      onChanged();
      return this;
    }

    private Object radiatorDescription_ = "";
    /**
     * <code>string radiatorDescription = 3;</code>
     */
    public String getRadiatorDescription() {
      Object ref = radiatorDescription_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        radiatorDescription_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string radiatorDescription = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRadiatorDescriptionBytes() {
      Object ref = radiatorDescription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        radiatorDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string radiatorDescription = 3;</code>
     */
    public Builder setRadiatorDescription(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      radiatorDescription_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string radiatorDescription = 3;</code>
     */
    public Builder clearRadiatorDescription() {

      radiatorDescription_ = getDefaultInstance().getRadiatorDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string radiatorDescription = 3;</code>
     */
    public Builder setRadiatorDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      radiatorDescription_ = value;
      onChanged();
      return this;
    }

    private Object radiatorLocation_ = "";
    /**
     * <code>string radiatorLocation = 4;</code>
     */
    public String getRadiatorLocation() {
      Object ref = radiatorLocation_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        radiatorLocation_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string radiatorLocation = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRadiatorLocationBytes() {
      Object ref = radiatorLocation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        radiatorLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string radiatorLocation = 4;</code>
     */
    public Builder setRadiatorLocation(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      radiatorLocation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string radiatorLocation = 4;</code>
     */
    public Builder clearRadiatorLocation() {

      radiatorLocation_ = getDefaultInstance().getRadiatorLocation();
      onChanged();
      return this;
    }
    /**
     * <code>string radiatorLocation = 4;</code>
     */
    public Builder setRadiatorLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      radiatorLocation_ = value;
      onChanged();
      return this;
    }

    private Object radiatorStatus_ = "";
    /**
     * <code>string radiatorStatus = 5;</code>
     */
    public String getRadiatorStatus() {
      Object ref = radiatorStatus_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        radiatorStatus_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string radiatorStatus = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRadiatorStatusBytes() {
      Object ref = radiatorStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        radiatorStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string radiatorStatus = 5;</code>
     */
    public Builder setRadiatorStatus(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      radiatorStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string radiatorStatus = 5;</code>
     */
    public Builder clearRadiatorStatus() {

      radiatorStatus_ = getDefaultInstance().getRadiatorStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string radiatorStatus = 5;</code>
     */
    public Builder setRadiatorStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      radiatorStatus_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:homeHeating.Radiator)
  }

  // @@protoc_insertion_point(class_scope:homeHeating.Radiator)
  private static final com.proto.homeHeating.Radiator DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.proto.homeHeating.Radiator();
  }

  public static com.proto.homeHeating.Radiator getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Radiator>
      PARSER = new com.google.protobuf.AbstractParser<Radiator>() {
    @Override
    public Radiator parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Radiator(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Radiator> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Radiator> getParserForType() {
    return PARSER;
  }

  @Override
  public com.proto.homeHeating.Radiator getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

