// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeHeating.proto

package com.proto.homeHeating;

/**
 * Protobuf type {@code homeHeating.radiatorToUpdateRequest}
 */
public  final class radiatorToUpdateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:homeHeating.radiatorToUpdateRequest)
    radiatorToUpdateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use radiatorToUpdateRequest.newBuilder() to construct.
  private radiatorToUpdateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private radiatorToUpdateRequest() {
    radiatorId_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private radiatorToUpdateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            radiatorId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.proto.homeHeating.HomeHeating.internal_static_homeHeating_radiatorToUpdateRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.proto.homeHeating.HomeHeating.internal_static_homeHeating_radiatorToUpdateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.proto.homeHeating.radiatorToUpdateRequest.class, com.proto.homeHeating.radiatorToUpdateRequest.Builder.class);
  }

  public static final int RADIATORID_FIELD_NUMBER = 1;
  private int radiatorId_;
  /**
   * <code>int32 radiatorId = 1;</code>
   */
  public int getRadiatorId() {
    return radiatorId_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (radiatorId_ != 0) {
      output.writeInt32(1, radiatorId_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (radiatorId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, radiatorId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.proto.homeHeating.radiatorToUpdateRequest)) {
      return super.equals(obj);
    }
    com.proto.homeHeating.radiatorToUpdateRequest other = (com.proto.homeHeating.radiatorToUpdateRequest) obj;

    boolean result = true;
    result = result && (getRadiatorId()
        == other.getRadiatorId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RADIATORID_FIELD_NUMBER;
    hash = (53 * hash) + getRadiatorId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.proto.homeHeating.radiatorToUpdateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.homeHeating.radiatorToUpdateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.homeHeating.radiatorToUpdateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.homeHeating.radiatorToUpdateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.homeHeating.radiatorToUpdateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.homeHeating.radiatorToUpdateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.homeHeating.radiatorToUpdateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.homeHeating.radiatorToUpdateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.homeHeating.radiatorToUpdateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.proto.homeHeating.radiatorToUpdateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.homeHeating.radiatorToUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.homeHeating.radiatorToUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.proto.homeHeating.radiatorToUpdateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code homeHeating.radiatorToUpdateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:homeHeating.radiatorToUpdateRequest)
      com.proto.homeHeating.radiatorToUpdateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.homeHeating.HomeHeating.internal_static_homeHeating_radiatorToUpdateRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.homeHeating.HomeHeating.internal_static_homeHeating_radiatorToUpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.homeHeating.radiatorToUpdateRequest.class, com.proto.homeHeating.radiatorToUpdateRequest.Builder.class);
    }

    // Construct using com.proto.homeHeating.radiatorToUpdateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      radiatorId_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.proto.homeHeating.HomeHeating.internal_static_homeHeating_radiatorToUpdateRequest_descriptor;
    }

    @Override
    public com.proto.homeHeating.radiatorToUpdateRequest getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public com.proto.homeHeating.radiatorToUpdateRequest build() {
      com.proto.homeHeating.radiatorToUpdateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.proto.homeHeating.radiatorToUpdateRequest buildPartial() {
      com.proto.homeHeating.radiatorToUpdateRequest result = new com.proto.homeHeating.radiatorToUpdateRequest(this);
      result.radiatorId_ = radiatorId_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.proto.homeHeating.radiatorToUpdateRequest) {
        return mergeFrom((com.proto.homeHeating.radiatorToUpdateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.proto.homeHeating.radiatorToUpdateRequest other) {
      if (other == getDefaultInstance()) return this;
      if (other.getRadiatorId() != 0) {
        setRadiatorId(other.getRadiatorId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.proto.homeHeating.radiatorToUpdateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.proto.homeHeating.radiatorToUpdateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int radiatorId_ ;
    /**
     * <code>int32 radiatorId = 1;</code>
     */
    public int getRadiatorId() {
      return radiatorId_;
    }
    /**
     * <code>int32 radiatorId = 1;</code>
     */
    public Builder setRadiatorId(int value) {

      radiatorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 radiatorId = 1;</code>
     */
    public Builder clearRadiatorId() {

      radiatorId_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:homeHeating.radiatorToUpdateRequest)
  }

  // @@protoc_insertion_point(class_scope:homeHeating.radiatorToUpdateRequest)
  private static final com.proto.homeHeating.radiatorToUpdateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.proto.homeHeating.radiatorToUpdateRequest();
  }

  public static com.proto.homeHeating.radiatorToUpdateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<radiatorToUpdateRequest>
      PARSER = new com.google.protobuf.AbstractParser<radiatorToUpdateRequest>() {
    @Override
    public radiatorToUpdateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new radiatorToUpdateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<radiatorToUpdateRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<radiatorToUpdateRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public com.proto.homeHeating.radiatorToUpdateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

